-- Cấu hình charset để hỗ trợ tiếng Việt
CREATE DATABASE IF NOT EXISTS CuaHangMayTinh DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE CuaHangMayTinh;

-- 1. BẢNG DANH MỤC CƠ BẢN
CREATE TABLE NHANVIEN (
    MaNV VARCHAR(20) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    GioiTinh NVARCHAR(10),
    NamSinh VARCHAR(20),
    SDT VARCHAR(20),
    DiaChi NVARCHAR(255),
    ChucVu NVARCHAR(50),
    SoNgayNghi INT DEFAULT 0,
    CaLamViec NVARCHAR(50),
    TrangThai NVARCHAR(50) DEFAULT 'Đang làm việc',
    MatKhau VARCHAR(50) DEFAULT '123'
);

CREATE TABLE KHACHHANG (
    MaKH VARCHAR(20) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    GioiTinh NVARCHAR(10),
    NamSinh VARCHAR(20),
    SDT VARCHAR(20),
    DiaChi NVARCHAR(255),
    TrangThai NVARCHAR(50) DEFAULT 'Hoạt động'
);

CREATE TABLE NHACUNGCAP (
    MaNCC VARCHAR(20) PRIMARY KEY,
    TenNCC NVARCHAR(150) NOT NULL,
    DiaChi NVARCHAR(255),
    SDT VARCHAR(20),
    TrangThai NVARCHAR(50) DEFAULT 'Hoạt động'
);

-- 2. BẢNG SẢN PHẨM & KHO
CREATE TABLE SANPHAM (
    MaSP VARCHAR(20) PRIMARY KEY,
    TenSP NVARCHAR(150) NOT NULL,
    LoaiSP NVARCHAR(50),
    MaNCC VARCHAR(20),
    GiaBan DECIMAL(18,2) NOT NULL,
    TGBaoHanh INT DEFAULT 0 COMMENT 'Thời gian bảo hành tính bằng tháng',
    TrangThai NVARCHAR(50) DEFAULT 'Đang kinh doanh',
    CONSTRAINT FK_SANPHAM_NCC FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);

-- 3. BẢNG NGHIỆP VỤ NHẬP HÀNG
CREATE TABLE PHIEUNHAP (
    MaPN VARCHAR(20) PRIMARY KEY,
    MaNV VARCHAR(20) NOT NULL,
    MaNCC VARCHAR(20) NOT NULL,
    NgayNhap DATETIME DEFAULT CURRENT_TIMESTAMP,
    TongTien DECIMAL(18,2) DEFAULT 0,
    CONSTRAINT FK_PN_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);

CREATE TABLE CHITIETPHIEUNHAP (
    MaPN VARCHAR(20),
    MaSP VARCHAR(20),
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    DonGiaNhap DECIMAL(18,2) NOT NULL,
    PRIMARY KEY (MaPN, MaSP),
    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MaPN) REFERENCES PHIEUNHAP(MaPN),
    CONSTRAINT FK_CTPN_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

-- 4. BẢNG NGHIỆP VỤ XUẤT/BÁN HÀNG
CREATE TABLE HOADON (
    MaHD VARCHAR(20) PRIMARY KEY,
    MaNV VARCHAR(20) NOT NULL,
    MaKH VARCHAR(20) NOT NULL,
    NgayLap DATETIME DEFAULT CURRENT_TIMESTAMP,
    TongTien DECIMAL(18,2) DEFAULT 0,
    CONSTRAINT FK_HD_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_HD_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);

-- 5. BẢNG ĐẶC THÙ NGÀNH: QUẢN LÝ SERI VÀ BẢO HÀNH
CREATE TABLE SERISANPHAM (
    MaSeri VARCHAR(50) PRIMARY KEY COMMENT 'Mã Serial hoặc IMEI độc nhất',
    MaSP VARCHAR(20) NOT NULL,
    MaPN VARCHAR(20) NULL COMMENT 'Sản phẩm này được nhập từ phiếu nào',
    MaHD VARCHAR(20) NULL COMMENT 'Sản phẩm này xuất ra bán trong hóa đơn nào',
    TinhTrang NVARCHAR(50) DEFAULT 'Trong kho' COMMENT 'Trong kho, Đã bán, Đang bảo hành, Lỗi',
    CONSTRAINT FK_SERI_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
    CONSTRAINT FK_SERI_PN FOREIGN KEY (MaPN) REFERENCES PHIEUNHAP(MaPN),
    CONSTRAINT FK_SERI_HD FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
);

CREATE TABLE CHITIETHOADON (
    MaHD VARCHAR(20),
    MaSeri VARCHAR(50),
    DonGiaBan DECIMAL(18,2) NOT NULL,
    PRIMARY KEY (MaHD, MaSeri),
    CONSTRAINT FK_CTHD_HD FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    CONSTRAINT FK_CTHD_SERI FOREIGN KEY (MaSeri) REFERENCES SERISANPHAM(MaSeri)
);

CREATE TABLE PHIEUBAOHANH (
    MaPBH VARCHAR(20) PRIMARY KEY,
    MaSeri VARCHAR(50) NOT NULL,
    MaKH VARCHAR(20) NOT NULL,
    MaNV VARCHAR(20) NOT NULL,
    NgayTiepNhan DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayTraDuKien DATETIME,
    MoTaLoi NVARCHAR(500),
    TinhTrang NVARCHAR(50) DEFAULT 'Đang xử lý',
    ChiPhi DECIMAL(18,2) DEFAULT 0,
    CONSTRAINT FK_PBH_SERI FOREIGN KEY (MaSeri) REFERENCES SERISANPHAM(MaSeri),
    CONSTRAINT FK_PBH_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT FK_PBH_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);
